package fr.formation.entities;
// Generated 17 mai 2021 � 15:50:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AfpaEmployes generated by hbm2java
 */
@Entity
@Table(name = "AFPA_EMPLOYES", schema = "PROJETFULLSTACK")
public class AfpaEmployes implements java.io.Serializable {

	private BigDecimal idemploye;
	private AfpaRoles afpaRoles;
	private AfpaDepartements afpaDepartements= new AfpaDepartements();
	private AfpaProjet afpaProjet= new AfpaProjet();
	private String mail;
	private String nom;
	private String prenom;
	private String pwd;

	public AfpaEmployes() {
	}

	public AfpaEmployes(BigDecimal idemploye) {
		this.idemploye = idemploye;
	}

	public AfpaEmployes(BigDecimal idemploye, AfpaRoles afpaRoles, AfpaDepartements afpaDepartements,
			AfpaProjet afpaProjet, String mail, String nom, String prenom, String pwd) {
		this.idemploye = idemploye;
		this.afpaRoles = afpaRoles;
		this.afpaDepartements = afpaDepartements;
		this.afpaProjet = afpaProjet;
		this.mail = mail;
		this.nom = nom;
		this.prenom = prenom;
		this.pwd = pwd;
	}

	@Id
	@SequenceGenerator(name="AFPA_EMPLOYES_SEQ", sequenceName = "AFPA_EMPLOYES_SEQ", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AFPA_EMPLOYES_SEQ")
	@Column(name = "IDEMPLOYE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdemploye() {
		return this.idemploye;
	}



	

	@Override
	public String toString() {
		return "AfpaEmployes [idemploye=" + idemploye + ", afpaDepartements=" + afpaDepartements + ", afpaProjet="
				+ afpaProjet + ", nom=" + nom + ", prenom=" + prenom + "]";
	}

	public void setIdemploye(BigDecimal idemploye) {
		this.idemploye = idemploye;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDROLE")
	public AfpaRoles getAfpaRoles() {
		return this.afpaRoles;
	}

	public void setAfpaRoles(AfpaRoles afpaRoles) {
		this.afpaRoles = afpaRoles;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	//@JsonIgnore
	@JoinColumn(name = "IDDEP")
	public AfpaDepartements getAfpaDepartements() {
		return this.afpaDepartements;
	}

	public void setAfpaDepartements(AfpaDepartements afpaDepartements) {
		this.afpaDepartements = afpaDepartements;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDPROJ")
	public AfpaProjet getAfpaProjet() {
		return this.afpaProjet;
	}

	public void setAfpaProjet(AfpaProjet afpaProjet) {
		this.afpaProjet = afpaProjet;
	}

	@Column(name = "MAIL")
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "PWD")
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	

}
