package fr.formation.entities;
// Generated 17 mai 2021 � 15:50:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AfpaRoles generated by hbm2java
 */
@Entity
@Table(name = "AFPA_ROLES", schema = "PROJETFULLSTACK")
public class AfpaRoles implements java.io.Serializable {

	private BigDecimal idrole;
	private String libelle;
	private Set<AfpaEmployes> afpaEmployeses = new HashSet<AfpaEmployes>(0);

	public AfpaRoles() {
	}

	public AfpaRoles(BigDecimal idrole) {
		this.idrole = idrole;
	}

	public AfpaRoles(BigDecimal idrole, String libelle, Set<AfpaEmployes> afpaEmployeses) {
		this.idrole = idrole;
		this.libelle = libelle;
		this.afpaEmployeses = afpaEmployeses;
	}

	@Id

	@Column(name = "IDROLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdrole() {
		return this.idrole;
	}

	public void setIdrole(BigDecimal idrole) {
		this.idrole = idrole;
	}

	@Column(name = "LIBELLE")
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "afpaRoles")
	public Set<AfpaEmployes> getAfpaEmployeses() {
		return this.afpaEmployeses;
	}

	public void setAfpaEmployeses(Set<AfpaEmployes> afpaEmployeses) {
		this.afpaEmployeses = afpaEmployeses;
	}

}
