package fr.formation.entities;
// Generated 17 mai 2021 � 15:50:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AfpaModules generated by hbm2java
 */
@Entity
@Table(name = "AFPA_MODULES", schema = "PROJETFULLSTACK")
public class AfpaModules implements java.io.Serializable {

	private BigDecimal idmodule;
	private AfpaProjet afpaProjet;
	private Date datedebut;
	private Date datefinestimee;
	private Date datefinreel;
	private String nom;
	private Set<AfpaTaches> afpaTacheses = new HashSet<AfpaTaches>(0);

	public AfpaModules() {
	}

	public AfpaModules(BigDecimal idmodule) {
		this.idmodule = idmodule;
	}

	public AfpaModules(BigDecimal idmodule, AfpaProjet afpaProjet, Date datedebut, Date datefinestimee,
			Date datefinreel, String nom, Set<AfpaTaches> afpaTacheses) {
		this.idmodule = idmodule;
		this.afpaProjet = afpaProjet;
		this.datedebut = datedebut;
		this.datefinestimee = datefinestimee;
		this.datefinreel = datefinreel;
		this.nom = nom;
		this.afpaTacheses = afpaTacheses;
	}

	@Id
	@SequenceGenerator(name="AFPA_MODULES_SEQ", sequenceName = "AFPA_MODULES_SEQ", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AFPA_MODULES_SEQ")
	@Column(name = "IDMODULE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdmodule() {
		return this.idmodule;
	}

	public void setIdmodule(BigDecimal idmodule) {
		this.idmodule = idmodule;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FKMODPROJ")
	public AfpaProjet getAfpaProjet() {
		return this.afpaProjet;
	}

	public void setAfpaProjet(AfpaProjet afpaProjet) {
		this.afpaProjet = afpaProjet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUT", length = 7)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINESTIMEE", length = 7)
	public Date getDatefinestimee() {
		return this.datefinestimee;
	}

	public void setDatefinestimee(Date datefinestimee) {
		this.datefinestimee = datefinestimee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREEL", length = 7)
	public Date getDatefinreel() {
		return this.datefinreel;
	}

	public void setDatefinreel(Date datefinreel) {
		this.datefinreel = datefinreel;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "afpaModules")
	public Set<AfpaTaches> getAfpaTacheses() {
		return this.afpaTacheses;
	}

	public void setAfpaTacheses(Set<AfpaTaches> afpaTacheses) {
		this.afpaTacheses = afpaTacheses;
	}

}
