package fr.formation.entities;
// Generated 17 mai 2021 � 15:50:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AfpaProjet generated by hbm2java
 */
@Entity
@Table(name = "AFPA_PROJET", schema = "PROJETFULLSTACK")
public class AfpaProjet implements java.io.Serializable {

	private BigDecimal idprojet;
	private String client;
	private BigDecimal code;
	private Date datedebut;
	private Date datefinestimee;
	private Date datefinreel;
	private String description;
	private String titre;
	private String type;
	private Set<AfpaEmployes> afpaEmployeses = new HashSet<AfpaEmployes>(0);
	private Set<AfpaModules> afpaModuleses = new HashSet<AfpaModules>(0);

	public AfpaProjet() {
	}

	public AfpaProjet(BigDecimal idprojet) {
		this.idprojet = idprojet;
	}

	public AfpaProjet(BigDecimal idprojet, String client, BigDecimal code, Date datedebut, Date datefinestimee,
			Date datefinreel, String description, String titre, String type, Set<AfpaEmployes> afpaEmployeses,
			Set<AfpaModules> afpaModuleses) {
		this.idprojet = idprojet;
		this.client = client;
		this.code = code;
		this.datedebut = datedebut;
		this.datefinestimee = datefinestimee;
		this.datefinreel = datefinreel;
		this.description = description;
		this.titre = titre;
		this.type = type;
		this.afpaEmployeses = afpaEmployeses;
		this.afpaModuleses = afpaModuleses;
	}

	@Id
	@SequenceGenerator(name="AFPA_PROJET_SEQ", sequenceName = "AFPA_PROJET_SEQ", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AFPA_PROJET_SEQ")
	@Column(name = "IDPROJET", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdprojet() {
		return this.idprojet;
	}

	public void setIdprojet(BigDecimal idprojet) {
		this.idprojet = idprojet;
	}

	@Column(name = "CLIENT")
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "CODE", precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUT", length = 7)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINESTIMEE", length = 7)
	public Date getDatefinestimee() {
		return this.datefinestimee;
	}

	public void setDatefinestimee(Date datefinestimee) {
		this.datefinestimee = datefinestimee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREEL", length = 7)
	public Date getDatefinreel() {
		return this.datefinreel;
	}

	public void setDatefinreel(Date datefinreel) {
		this.datefinreel = datefinreel;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TITRE")
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afpaProjet")
	@JsonIgnore
	public Set<AfpaEmployes> getAfpaEmployeses() {
		return this.afpaEmployeses;
	}

	public void setAfpaEmployeses(Set<AfpaEmployes> afpaEmployeses) {
		this.afpaEmployeses = afpaEmployeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afpaProjet")
	@JsonIgnore
	public Set<AfpaModules> getAfpaModuleses() {
		return this.afpaModuleses;
	}

	public void setAfpaModuleses(Set<AfpaModules> afpaModuleses) {
		this.afpaModuleses = afpaModuleses;
	}

}
